### ISSUE TITLE
Use Sources UUID for cluster UUID

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta#112]
## User Story
As a user setting up korekuta I need my cluster identifier to match the sources UUID so that data is properly processed in cost management. 

## Acceptance Criteria
- [ ] A new arg exists for the setup command/ansible role for the sources UUID
- [ ] Korekuta should no longer assign a new UUID
- [ ] Follow up with Dayle to make sure this new flow is covered in the docs

**Comment by chambridge** [comment]
After consulting the [current setup documentation](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_adding_sources_cost#assembly_adding_ocp_sources). Existing flow with sources, this is not needed and we should be able to move on to the following issue as an alternative: https://github.com/project-koku/korekuta/issues/113
