### ISSUE TITLE
Fetching the OpenShift Cluster ID from cluster resource object instead of generating a UUID

### ISSUE THREAD

**Issue by dccurtis** [project-koku/korekuta#113]
## User Story
As a user I would like to use my OpenShift Cluster Manager ID as the identifier used in the Korekuta-Cost Management on boarding.

## Impacts
API, UI, Docs

## Assumptions and Questions
- @chambridge has some experience with this and can provide details.
- We would like to minimize the number of identifiers the user has to understand when on boarding an OpenShift cluster to cost management through Platform Sources.
- Research to see how feasible it is to get the OCM cluster ID and scope out the work needed to provide the ID to the Korekuta setup. 
- Q: Are there any OpenShift version checks to be concerned with (i.e. only available with OCP4) and if so, do we have to maintain backwards compatibility with OCP 3.11.  Maybe in those cases we could fall back to generating a uuid?

## Acceptance Criteria

- [ ] Document including the steps needed to get the OCM cluster ID and general scope as to how it would be implemented in korekuta.

**Comment by lcouzens** [comment]
Verified
