### ISSUE TITLE
Support Tag Inheritance with OpenShift

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta#116]
## User Story
As a customer, I want to apply labels in OpenShift for cost management more efficiently, so that I can communicate common labels like cost center, environment type, etc. without needing to apply these labels to every pod.

## Impacts
- Operator Metering Resource

## Assumptions
- A label applied to a node will be inherited by the pods running on that node
- We should ingest node labels and pod labels "purely" without modification in korekuta / Operator Metering.
- In our daily_summary table SQL we can do the work to combine node labels into the pod labels field.

## Implementation Details
- Create a data source for node labels like:
https://github.com/project-koku/korekuta/blob/master/roles/setup/files/kube-pod-labels_report_data_source.yaml
- Update the prometheus query to pull from kube_node_labels

- Create a report query for nodes like:
https://github.com/project-koku/korekuta/blob/master/roles/setup/files/pod-labels_report_generation_query.yaml

-Create a report view from the report query like:
https://github.com/project-koku/korekuta/blob/master/roles/setup/files/pod-labels_report_data_source.yaml

-Update the following report query to join hourly pod labels with the hourly node labels based on the node the pod was running on:
https://github.com/project-koku/korekuta/blob/1f34747258c091fff9a5cc1d30fde5469aa7bce4/roles/setup/files/hccm_openshift_usage_report_generation_query.yaml

-If necessary a separate report query and view could be created to join this data together and the above query updated with the new view.

## Acceptance Criteria
- Verify that the labels associated with a node are included with the pod labels if the pod was running on that node

**Comment by lcouzens** [comment]
Verified!
