### ISSUE TITLE
Hitting dependency errors while running the Korekuta playbook

### ISSUE THREAD

**Issue by lcouzens** [project-koku/korekuta#117]
After a small investigation with Chris it looks like we could benefit from including the following dep requirements.

```
  - python_requirements_facts:
        dependencies:
          - openshift
          - requests
```

**Comment by lcouzens** [comment]
@chambridge So when running the playbook now if these deps are missing it should fetch them?

**Comment by chambridge** [comment]
No, it doesn't fetch them, just alerts the user that they are missing but necessary.
https://docs.ansible.com/ansible/2.7/modules/python_requirements_facts_module.html

So now it should be more clear that these need to be installed as dependencies.

We could potentially do another feature that attempts to install them, but trying to balance improvements here vs. the work to start on the operator.

**Comment by lcouzens** [comment]
Yeh thats a fair point and makes sense. Just wanted to double check :+1:
