### ISSUE TITLE
Provide installation and usage documentation

### ISSUE THREAD

**Issue by nlcwong** [project-koku/korekuta#47]
**Describe the bug**
If a user tries to download this project to use (e.g. install and execute), the readme does not contain information on installation or usage.

**To Reproduce**
1. Go to https://github.com/project-koku/korekuta
2. Under the "<> Code" tab, find and open file: README.md

**Expected behavior**
Besides documentation on how to develop this playbook, documentation on how/where this playbook should be installed and run.

**Additional context**
This is an enhancement ask from UI/Docs in where we are trying to make koku's OCP onboarding flow as a quick read and perhaps consistent with providing documentation on external tools through links to the external tool's doc location.  For instance, for all instructions that tells a user how to add a policy w/in AWS, we will include a link to that doc and instead provide the exact information they would need to input (requirements for koku functionality and nothing else) with the understanding that the admin would have some expertise in knowing how to add a policy w/in AWS and/or is comfortable going to the AWS website to find the step by step procedures.  We are treating documentation about korekuta the same as if it was like AWS instructions.

**Comment by chambridge** [comment]
Could link to RTD, but would prefer users who have downloaded the korekuta packate to have all the data they need to perform install.

**Comment by adberglund** [comment]
Add a README to the repo with install instructions
