### ISSUE TITLE
Update Reports to use new Operator Metering Resources

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta#64]
Operator Metering resources have changes recently and our YAML needs to be updated to use the new resources. 

#### Chance
so
you will certainly need to update what you're using to upgrade
and trying to upgrade an existing install is not going to work with the changes we've made
so it'll be a fresh install required
i do have some scripts, let me try and get them, they're not super general purpose, mostly stuff i used to do some of the changes.
@aberglun so this `jq` script can be used with json files using `jq`, or yaml files using `faq`, and can be invoked like:
`faq -f yaml -o yaml -M -F update-rgqs.jq your-report-generation-query.yaml`
or `jq -M -F update-rgqs.jq your-report-generation-query.json`
https://gist.github.com/chancez/2b4b1a92358a730a504220476395f5fa

then you'll need to change all occurrences of `ReportGenerationQuery` to `ReportQuery` (this script was written before that rename)
additionally, ReportPrometheusQuery is gone, instead the content of the ReportPrometheusQuery's promQL expression, goes into a ReportDataSource directly.
I suggest doing a manual install, and then surveying the default resource it creates (ReportDataSources, and ReportQueries) to get a better idea

#### Andrew
Yeah, I was going to say, I can look at the repo or an install to figure that out.
Okay. Two of the clusters we had been pulling data from are OpenShift 3.11. Are these newest changes compatible in 3.11 or should I just abandon those clusters to ride the :ocean: of the future?

#### Chance
should be fine with 3.11

#### Andrew
Great.

#### Chance
Oh, and any views you create are going to be done using a ReportDataSource + ReportQuery rather than setting spec.view.disabled to false (or leaving it empty) for a ReportQuery

**Comment by adberglund** [comment]
@lcouzens This was work in korekuta, so I don't know that it directly needs a test. The end result is that an OpenShift 4 cluster with a new release of operator-metering can be ingested as a data source.

**Comment by lcouzens** [comment]
Verified
