### ISSUE TITLE
Gain access to Operator Metering reports API

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta#69]
Our use of the `metering-operator` service account does not appear to work with the newest version of Operator Metering. An attempt to add the reporting-viewer role to a service account did not appear to work, but might have been user error. We should probably discuss further with the Operator Metering team and determine if there is an issue on their end or if we need to create our own service account user with access to the report API.

**Comment by adberglund** [comment]
@lcouzens Similarly, this was work in korekuta, so I don't know that it directly needs a test. The end result is that an OpenShift 4 cluster with a new release of operator-metering can be ingested as a data source.

**Comment by lcouzens** [comment]
Verified
