### ISSUE TITLE
allow multiple OCP clusters to be collected from one linux user korekuta-master

### ISSUE THREAD

**Issue by newgoliath** [project-koku/korekuta#74]
**Is your feature request related to a problem? Please describe.**
It's a source of confusion and toil for Linux system admins to create a new linux user account for every OCP cluster deployed. 

**Describe the solution you'd like**
I'd like to be able to collect usage for multiple OCP clusters from the same linux host and user.
- use `ocp_usage.sh --setup` many time with different API endpoints and service account
- use `ocp_usage.sh --list` to see those API endpoints, service accounts, and cluster IDs
- use `ocp_usage.sh --delete <cluster_id>` to remove a cluster
- use `ocp_usage.sh --setup` keyed on API endpoint so service account token can be updated if necessary

**Describe alternatives you've considered**
- I've considered putting `korekuta-master` in a container.
- I've considered trying python virtual environments.

**Additional context**

As a super bonus, I'd like to be able to associate an OCP cluster with an insights organization from the same collector host.  We serve many billable orgs, and all of them are served from one host.

- `labs.opentlc.com` bills GPTE
- `rhpds.opentlc.com` bills the OpenShift BU and Middleware BUs
- `spp.redhat.com` support special events with many different billees.

To make it happen, each cluster would be associated with an insights `basic auth` user. The collector would run insights with the appropriate basic auth user.

Much of this is migrating to Tower.  We'll keep you posted.

**Comment by newgoliath** [comment]
Also needed --OC_CLIENT='/path/to/client --config /path/to/config' to cover multiple versions of `oc` and multiple kubeconfigs.

**Comment by newgoliath** [comment]
closed by #80

**Comment by infinitewarp** [comment]
Closing per aforementioned comment…
