### ISSUE TITLE
Not all namespaces/projects come through our reports

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta#78]
**Describe the bug**
Many built in OpenShift projects are not making it into our reports. Our reports use many `JOIN`s and it's possible we are dropping data.

**Expected behavior**
All projects should come through.

**Additional context**
Let's run an ad-hoc report using a modified version of our report query using `LEFT JOIN`s instead of `JOIN`s and see if we get back more projects.

**Comment by newgoliath** [comment]
confirmed.  I'm seeing: 
![Screen Shot 2019-06-19 at 09 06 53](https://user-images.githubusercontent.com/4221612/59768047-a0e78d00-9271-11e9-9411-b4b5fb06f27c.png)

**Comment by adberglund** [comment]
We should just be able to see all of the OpenShift default projects in the UI now. This was a korekuta / operator metering report change.

**Comment by chambridge** [comment]
@adberglund Feels like this should be closed with https://github.com/project-koku/korekuta/pull/80

**Comment by lcouzens** [comment]
Verified! Sorry I took so long :D
