### ISSUE TITLE
Multi-cluster korekuta use is including files from other clusters in payload

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta#84]
**Describe the bug**
We have added an argument to the collect role to specify which cluster is being processed, but data from other clusters makes it into the payload. 

**Expected behavior**
Only the files for the specified cluster should come in the payload.

**Comment by chambridge** [comment]
I don't think this is a real bug. I think we were seeing good and bad formatted versions of the OpenShift data here. OpenShift reports should have been prefixed with the assembly UUID, but lacking that knowledge a bug was injected that utilized the cluster_id as the prefix. So we were just seeing a directory (which is per cluster_id) with the old and new state at the same time.

**Comment by adberglund** [comment]
Agreed @chambridge I think https://github.com/project-koku/korekuta/pull/87 fixed the real issue here. Closing this one.
